name: Test MLOps Pipeline

on:
  pull_request:
    paths:
      - 'src/**'
      - 'data/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pipeline tests
        run: |
          python test_workflow.py
      
      - name: Test Docker build
        run: |
          docker build -t diabetes-mlops-test .
      
      - name: Test Docker run
        run: |
          docker run --rm -d --name test-container -p 8501:8501 diabetes-mlops-test
          sleep 10
          curl -f http://localhost:8501/_stcore/health || exit 1
          docker stop test-container
